<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
    'app_user' => [[], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/user']], [], [], []],
    'users_manager' => [[], ['_controller' => 'App\\Controller\\UsersManagerController::usersTable'], [], [['text', '/users-manager']], [], [], []],
    'security_login' => [[], ['_controller' => 'Symfony\\Bundle\\FrameworkBundle\\Controller\\RedirectController::urlRedirectAction'], [], [['text', '/login']], [], [], []],
    'security_logout' => [[], [], [], [['text', '/logout']], [], [], []],
    'users_managemer' => [[], ['_controller' => 'App\\Controller\\UsersManagerController::usersTable'], [], [['text', '/users-manager']], [], [], []],
    'user_details' => [[], ['_controller' => 'App\\Controller\\UserDetailsController::index'], [], [['text', '/user-details']], [], [], []],
    'delete_user' => [['id'], ['_controller' => 'App\\Controller\\UsersManagerController::deleteUser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/users-manager/delete']], [], [], []],
    'block_user' => [['id'], ['_controller' => 'App\\Controller\\UsersManagerController::blockUser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/users-manager/block']], [], [], []],
    'unblock_user' => [['id'], ['_controller' => 'App\\Controller\\UsersManagerController::unblockUser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/users-manager/unblock']], [], [], []],
    'App\Controller\RegistrationController::register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'App\Controller\SecurityController::login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/']], [], [], []],
    'App\Controller\SecurityController::logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
    'App\Controller\UserController::index' => [[], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/user']], [], [], []],
    'App\Controller\UserDetailsController::index' => [[], ['_controller' => 'App\\Controller\\UserDetailsController::index'], [], [['text', '/user-details']], [], [], []],
    'App\Controller\UsersManagerController::usersTable' => [[], ['_controller' => 'App\\Controller\\UsersManagerController::usersTable'], [], [['text', '/users-manager']], [], [], []],
    'App\Controller\UsersManagerController::deleteUser' => [['id'], ['_controller' => 'App\\Controller\\UsersManagerController::deleteUser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/users-manager/delete']], [], [], []],
    'App\Controller\UsersManagerController::blockUser' => [['id'], ['_controller' => 'App\\Controller\\UsersManagerController::blockUser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/users-manager/block']], [], [], []],
    'App\Controller\UsersManagerController::unblockUser' => [['id'], ['_controller' => 'App\\Controller\\UsersManagerController::unblockUser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/users-manager/unblock']], [], [], []],
];
