controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

security_login:
    path: /login
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction

security_logout:
    path: /logout
    
users_managemer:
    path: /users-manager
    controller: App\Controller\UsersManagerController::usersTable

user_details:
    path: /user-details
    controller: App\Controller\UserDetailsController::index

delete_user:
    path: /users-manager/delete/{id}
    controller: App\Controller\UsersManagerController::deleteUser

block_user:
    path: /users-manager/block/{id}
    controller: App\Controller\UsersManagerController::blockUser

unblock_user:
    path: /users-manager/unblock/{id}
    controller: App\Controller\UsersManagerController::unblockUser
